### ISSUE TITLE
question

### ISSUE THREAD

**Issue by lixiang957** [dgiorgio/openvas-source#1]
ERROR: Service 'gvm-master-stable-postgres' failed to build: The command '/bin/sh -c chmod +x ./build.sh && ./build.sh ${STAGE} ${DATABASE}' returned a non-zero code: 1

Containers can't be built
能看下你写的有问题吗

**Comment by dgiorgio** [comment]
How are you running?  is in the same directory as the .env file?

**Comment by lixiang957** [comment]
Direct command docker-compose -f ./docker-compose-build-postgres.yml build

**Comment by lixiang957** [comment]
you use -DBACKEND=POSTGRESQL

**Comment by lixiang957** [comment]
it is not the latest support

**Comment by dgiorgio** [comment]
The old project has been moved to the "[legacy branch](https://github.com/dgiorgio/gvm-docker/tree/legacy)".

A new simpler way to build the project has been added.

Support for postgres I used as a reference to this "[link](https://github.com/greenbone/gvmd/blob/gvmd-8.0/doc/postgres-HOWTO)" documentation.
I have not validated the use with postgres, soon I will do some tests.

**Comment by dgiorgio** [comment]
Postgres officially supported: https://github.com/dgiorgio/gvm-docker/commit/aca30de034ad7933de2ae5be62a32614ac5e3333
