### ISSUE TITLE
PDF Report Generation

### ISSUE THREAD

**Issue by cmattern68** [dgiorgio/openvas-source#11]
Hi,

I have some issue on generating PDF report. Each pdf reports generated are of size of 0 bytes. Latex seems to be installed on ```gvm_gvm-gsa_1```, ```gvm_gvm-gvmd_1``` and ```gvm_gvm-postgres_1```. 

A quick check on the logs of ```gvm_gvm-gvmd_1``` show me this error:
```
==> /usr/local/var/log/gvm/gvmd.log <==
event alert:MESSAGE:2021-09-15 11h22.05 CEST:32503: The alert Scan Terminé was triggered (Event: Task status changed to 'Done', Condition: Always)
md manage:WARNING:2021-09-15 11h22.05 CEST:32503: run_report_format_script: system failed with ret 256, 1, /usr/local/var/lib/gvm/gvmd/report_formats/7020b5a7-1ba2-4efe-983a-08dd63b63f23/c402cc3e-b531-11e1-9163-406186ea4fc5/generate /tmp/gvmd_XwoXuy/report.xml '<files><basedir>/tmp/gvmd_XwoXuy</basedir></files>' > /tmp/gvmd_XwoXuy/c402cc3e-b531-11e1-9163-406186ea4fc5-ToVUU9.pdf 2> /dev/null
```

Greenbone community is saying that this is caused by latex being not installed on the system, but latex seems to be present.
Have you faced the same issue and maybe have a workaround ?

Thanks !

**Comment by dgiorgio** [comment]
@cmattern68 Thanks for the report

I detected the problem this week.
I'm running some tests to solve this.

**Comment by dgiorgio** [comment]
@cmattern68 I solved the problem by installing the packages below.

`apt install texlive-fonts-recommended texlive-fonts-extra texlive-science`

If you need the fix urgently, you can install these packages in the 'gvm' container.
I will validate which packages are really needed, before generating a new docker image.

**Comment by dgiorgio** [comment]
https://github.com/greenbone/gvmd/blob/master/INSTALL.md#prerequisites-for-optional-features
```
apt-get install texlive-latex-extra --no-install-recommends
apt-get install texlive-fonts-recommended
```

**Comment by dgiorgio** [comment]
Created a new image with the correction.

https://github.com/dgiorgio/gvm-docker/commit/52f26787b93892821b1e3f83028a713675fef0f1

**Comment by cmattern68** [comment]
I can confirm that now it work without any issues ! Thank you !
