### ISSUE TITLE
No CVE displayed on dashboard

### ISSUE THREAD

**Issue by tkmru** [dgiorgio/openvas-source#2]
I launched the GVM with this command, but the CVE is not reflected in the dashboard.

```
docker run -p 80:80 -p 443:443 -p 9390-9393:9390-9393 dgiorgio/gvm-docker
```

Do you know what that is?

<img width="997" alt="スクリーンショット 2020-05-26 2 24 58" src="https://user-images.githubusercontent.com/1628214/82833116-1df69a00-9ef8-11ea-8129-8560045bc06b.png">

**Comment by dgiorgio** [comment]
This image has been deprecated (https://hub.docker.com/repository/docker/dgiorgio/gvm-docker), is in the 'legacy' branch.

All services are executed in a single container, check the logs, if the services are running.

If possible, use the updated images, where each service runs in an isolated container.
https://github.com/dgiorgio/gvm-docker/blob/master/docker-compose/stable/docker-compose.yml

**Comment by tkmru** [comment]
When I used the latest master branch, the CVE information was not reflected 3 days ago, but it was reflected now.
Building a GVM is difficult.
Thanks.
