### ISSUE TITLE
Openvas -u loop

### ISSUE THREAD

**Issue by mrcnpp** [dgiorgio/openvas-source#5]
After updating the SCAP feed 
the indicated process goes into a loop 
![image](https://user-images.githubusercontent.com/8047343/95979170-83054a80-0e1b-11eb-9671-99815389bab4.png)
and the web gui login return this error 
![image](https://user-images.githubusercontent.com/8047343/95979244-a29c7300-0e1b-11eb-8ae0-d0602cc839f9.png)

Could you give us a solution ?thanks

**Comment by dgiorgio** [comment]
GVMD only starts after openvas.
and openvas only starts after synchronizing the NVTs.
The first start is time-consuming due to synchronizations.
Wait for the synchronization of the NVTs, after that, follow the logs of the GVMD container.
