### ISSUE TITLE
Scan config could not be created by admin

### ISSUE THREAD

**Issue by eric-it6** [dgiorgio/openvas-source#8]
**GVM versions**
postgres-gvm: 11
gvmd: 20.8.0-1
openvas: 20.8.0-1
gsa: 20.8.0

Hi,
i guess you've already noticed, but I wanted to make sure. The Greenbone community feed is missing a VT, yet it is referenced. 
This creates an error when creating the configuration and causes a high load on the server. The error in the log looks like this:
`md manage:WARNING:2021-02-23 15h53.39 utc:1: insert_nvt_selectors: skipping NVT '1.3.6.1.4.1.25623.1.0.150081' from`
`import of config 'a1f217f4-22ae-4823-ac39-5f20127000b0' because the NVT does not have a family`
`md manage:WARNING:2021-02-23 15h53.39 utc:1: create_config_from_file: Internal error`
`event config:MESSAGE:2021-02-23 15h53.39 utc:1: Scan config could not be created by admin`
Post in the community: https://community.greenbone.net/t/skipping-nvt-1-3-6-1-4-1-25623-1-0-150081/8280

The developers have implemented a mechanism to work around this problem. More about it here: https://github.com/greenbone/gvmd/pull/1366

I haven't found a way to stop config creation yet. Could you give me some feedback if you are already working on the problem and when the next version will be released?

**Comment by dgiorgio** [comment]
Hi,
I didn't have this problem, I use a private feed.
https://github.com/dgiorgio/gvm-feed-server

I can create a fix for this, but first, I need to create an environment to simulate this problem.
Thanks for the report.

**Comment by eric-it6** [comment]
A big thanks to you!

The update has fixed the problem. The load is gone and nothing appears in the log.

Funnily enough, however, further syncs are now no longer written to the log. Are you aware of this behavior?

**Comment by eric-it6** [comment]
Hey,

the problem is that the sync is not running anymore, that's why there is nothing in the log. Unfortunately I did not get the cronjob from you to run. Maybe you could look over there again in the future. I have now solved the problem with a system level cronjob that triggers the command for the appropriate container.

Many greetings
Eric
